// Seed data: Brussels, matching the "Brussels in One Day" map.
// `wiki` is an English Wikipedia page title used to fetch a cover photo.
// `poses` are shot ideas shown in the sidebar for each spot.
window.SEED_CITY = {
  name: "Brussels",
  center: [50.8466, 4.3540],
  zoom: 15,
};

window.CATEGORIES = {
  sight: { label: "Sight", color: "#007AFF", emoji: "🏛️" },
  photo: { label: "Photo spot", color: "#AF52DE", emoji: "📸" },
  food: { label: "Food & drink", color: "#FF9500", emoji: "🧇" },
  shop: { label: "Shopping", color: "#34C759", emoji: "🛍️" },
  stay: { label: "Hotel", color: "#FF3B30", emoji: "🛏️" },
};

window.SEED_SPOTS = [
  {
    id: "grand-place",
    name: "Grand-Place",
    category: "sight",
    lat: 50.8467, lng: 4.3525,
    address: "Grand-Place, 1000 Bruxelles, Belgium",
    wiki: "Grand-Place",
    bestTime: "Before 9am for an empty square; blue hour for the lit-up facades",
    poses: [
      "Walk toward the camera with the Town Hall tower centred behind you",
      "Sit on the cobblestones, shot from low, with the gilded guildhalls filling the frame",
      "Over-the-shoulder look back from the corner by Rue au Beurre",
    ],
  },
  {
    id: "galeries",
    name: "Galeries Royales Saint-Hubert",
    category: "shop",
    lat: 50.8478, lng: 4.3548,
    address: "Galerie du Roi 5, 1000 Bruxelles, Belgium",
    wiki: "Royal_Galleries_of_Saint-Hubert",
    bestTime: "Early morning, before the shops open",
    poses: [
      "Stand in the centre of the arcade so the glass roof lines lead to you",
      "Candid shot window-shopping at a chocolatier",
    ],
  },
  {
    id: "manneken-pis",
    name: "Manneken Pis",
    category: "sight",
    lat: 50.8450, lng: 4.3500,
    address: "Rue de l'Étuve 46, 1000 Bruxelles, Belgium",
    wiki: "Manneken_Pis",
    bestTime: "Check the costume calendar, as he is dressed up most weeks",
    poses: ["Playful mirror pose beside the fountain (it's tiny, so stand close)"],
  },
  {
    id: "dandoy",
    name: "Maison Dandoy (waffles)",
    category: "food",
    lat: 50.8476, lng: 4.3517,
    address: "Rue au Beurre 31, 1000 Bruxelles, Belgium",
    wiki: "Maison_Dandoy",
    bestTime: "Mid-afternoon to skip the queue",
    poses: [
      "Waffle held up in the foreground with the storefront blurred behind",
      "Flat-lay of waffle and coffee on the table",
    ],
  },
  {
    id: "delirium",
    name: "Delirium Café",
    category: "food",
    lat: 50.8486, lng: 4.3537,
    address: "Impasse de la Fidélité 4, 1000 Bruxelles, Belgium",
    wiki: "Delirium_Café",
    bestTime: "Evening, when the alley lights are on",
    poses: ["Cheers shot in the lantern-lit alley"],
  },
  {
    id: "cathedral",
    name: "St. Michael and St. Gudula Cathedral",
    category: "sight",
    lat: 50.8478, lng: 4.3600,
    address: "Place Sainte-Gudule, 1000 Bruxelles, Belgium",
    wiki: "St._Michael_and_St._Gudula_Cathedral",
    bestTime: "Late afternoon sun on the facade",
    poses: ["Sit halfway up the front steps, shot from the bottom looking up"],
  },
  {
    id: "comic-center",
    name: "Centre Belge de la Bande Dessinée",
    category: "photo",
    lat: 50.8510, lng: 4.3594,
    address: "Rue des Sables 20, 1000 Bruxelles, Belgium",
    wiki: "Belgian_Comic_Strip_Center",
    bestTime: "Any time; the Art Nouveau hall has soft daylight",
    poses: ["Pose next to the giant Tintin rocket in the entrance hall"],
  },
  {
    id: "bozar",
    name: "BOZAR",
    category: "sight",
    lat: 50.8441, lng: 4.3597,
    address: "Rue Ravenstein 23, 1000 Bruxelles, Belgium",
    phone: "+32 2 507 82 00",
    website: "https://www.bozar.be",
    wiki: "Centre_for_Fine_Arts,_Brussels",
    bestTime: "Golden hour on the Art Deco exterior",
    poses: ["Walking past the curved facade, shot from across Rue Ravenstein"],
  },
  {
    id: "mim",
    name: "Musical Instruments Museum (Old England)",
    category: "photo",
    lat: 50.8429, lng: 4.3582,
    address: "Rue Montagne de la Cour 2, 1000 Bruxelles, Belgium",
    wiki: "Musical_Instruments_Museum_(Brussels)",
    bestTime: "Morning, when the light is soft on the ironwork",
    poses: [
      "Full-length shot in front of the Art Nouveau iron facade",
      "Rooftop café shot with the city skyline behind you",
    ],
  },
  {
    id: "mont-des-arts",
    name: "Mont des Arts",
    category: "photo",
    lat: 50.8437, lng: 4.3565,
    address: "Mont des Arts, 1000 Bruxelles, Belgium",
    wiki: "Mont_des_Arts",
    bestTime: "Sunset, looking down toward the Town Hall spire",
    poses: [
      "Back to the camera at the top of the stairs, looking out over the garden to the spire",
      "Sitting on the garden wall with the hedges forming leading lines",
      "Twirl shot in the middle of the stairs",
    ],
  },
  {
    id: "fine-arts",
    name: "Musées Royaux des Beaux-Arts",
    category: "sight",
    lat: 50.8418, lng: 4.3580,
    address: "Rue de la Régence 3, 1000 Bruxelles, Belgium",
    wiki: "Royal_Museums_of_Fine_Arts_of_Belgium",
    bestTime: "Weekday mornings are quietest",
    poses: ["Silhouette in front of a large canvas (check the photo rules first)"],
  },
  {
    id: "parc",
    name: "Parc de Bruxelles",
    category: "photo",
    lat: 50.8448, lng: 4.3640,
    address: "Rue Royale, 1000 Bruxelles, Belgium",
    wiki: "Brussels_Park",
    bestTime: "Autumn leaves, mid-morning",
    poses: ["Walking down the tree-lined central alley toward the Palace"],
  },
  {
    id: "palace",
    name: "Royal Palace of Brussels",
    category: "sight",
    lat: 50.8417, lng: 4.3620,
    address: "Rue Brederode 16, 1000 Bruxelles, Belgium",
    wiki: "Royal_Palace_of_Brussels",
    bestTime: "Open to visitors in summer only; facade any time",
    poses: ["Symmetrical centred shot through the gates"],
  },
  {
    id: "sablon",
    name: "Place du Grand Sablon",
    category: "food",
    lat: 50.8400, lng: 4.3555,
    address: "Place du Grand Sablon, 1000 Bruxelles, Belgium",
    wiki: "Place_du_Grand_Sablon",
    bestTime: "Weekend antiques market mornings",
    poses: ["Chocolate-shop window shot (Pierre Marcolini, Wittamer)"],
  },
  {
    id: "notre-dame-sablon",
    name: "Notre-Dame du Sablon",
    category: "photo",
    lat: 50.8397, lng: 4.3568,
    address: "Rue de la Régence 3B, 1000 Bruxelles, Belgium",
    wiki: "Church_of_Our_Blessed_Lady_of_the_Sablon",
    bestTime: "Sunny afternoons, when the stained glass glows inside",
    poses: ["Standing in the Gothic doorway, looking up"],
  },
  {
    id: "poelaert",
    name: "Grande Roue / Place Poelaert",
    category: "photo",
    lat: 50.8375, lng: 4.3527,
    address: "Place Poelaert, 1000 Bruxelles, Belgium",
    wiki: "Palace_of_Justice,_Brussels",
    bestTime: "Sunset, for the panorama over the Marolles",
    poses: ["Leaning on the railing with the city skyline behind you"],
  },
];

// More ready-made trips. Spot ids are prefixed per city so photos never mix.
(() => {
  const s = (id, name, category, lat, lng, address, wiki, bestTime, poses) =>
    ({ id, name, category, lat, lng, address, wiki, bestTime, poses });

  window.SEED_TRIPS = [
    {
      id: "bruges", name: "Bruges", center: [51.2070, 3.2260], zoom: 15,
      spots: [
        s("bg-markt", "Markt & Belfry", "sight", 51.2088, 3.2244, "Markt, 8000 Brugge, Belgium", "Belfry_of_Bruges",
          "Early morning before the tour groups; the colourful guild houses glow at sunset",
          ["Walk across the square with the Belfry tower behind you", "Sit by the horse carriages, shot from low"]),
        s("bg-rozenhoedkaai", "Rozenhoedkaai", "photo", 51.2073, 3.2275, "Rozenhoedkaai, 8000 Brugge, Belgium", "Rozenhoedkaai",
          "Blue hour, when the Belfry lights reflect in the canal",
          ["Lean on the canal wall, looking back over your shoulder, Belfry framed behind you", "Wide 0.5x shot with the canal leading to you"]),
        s("bg-burg", "Burg Square & City Hall", "sight", 51.2083, 3.2270, "Burg, 8000 Brugge, Belgium", "Bruges_City_Hall",
          "Golden hour on the Gothic facade", ["Symmetrical shot in front of the City Hall doors"]),
        s("bg-holy-blood", "Basilica of the Holy Blood", "sight", 51.2081, 3.2263, "Burg 13, 8000 Brugge, Belgium", "Basilica_of_the_Holy_Blood",
          "Late morning", ["Standing in the ornate gilded doorway"]),
        s("bg-bonifacius", "Bonifacius Bridge", "photo", 51.2049, 3.2253, "Groeninge, 8000 Brugge, Belgium", null,
          "Morning, before the crowds", ["Sit on the little stone bridge with the ivy-covered houses behind"]),
        s("bg-our-lady", "Church of Our Lady", "sight", 51.2048, 3.2245, "Mariastraat, 8000 Brugge, Belgium", "Church_of_Our_Lady,_Bruges",
          "Weekday mornings", ["Look up at the brick spire from the garden side"]),
        s("bg-begijnhof", "Begijnhof", "photo", 51.2002, 3.2235, "Begijnhof 24, 8000 Brugge, Belgium", "Princely_Beguinage_Ten_Wijngaerde",
          "April for the daffodils; keep quiet, it's a peaceful courtyard", ["Walking along the white houses under the trees"]),
        s("bg-minnewater", "Minnewater (Lake of Love)", "photo", 51.1990, 3.2252, "Minnewater, 8000 Brugge, Belgium", "Minnewater",
          "Sunrise, with mist on the water", ["Romantic over-the-shoulder look on the bridge", "Swans in the foreground, you in the background"]),
        s("bg-halve-maan", "De Halve Maan Brewery", "food", 51.2032, 3.2245, "Walplein 26, 8000 Brugge, Belgium", "De_Halve_Maan_Brewery",
          "Afternoon terrace", ["Cheers with a Brugse Zot on the terrace"]),
        s("bg-windmills", "Kruisvest Windmills", "photo", 51.2142, 3.2364, "Kruisvest, 8000 Brugge, Belgium", null,
          "Sunset, when the windmills are backlit", ["Walking along the path with a windmill on the hill behind you"]),
      ],
    },
    {
      id: "ghent", name: "Ghent", center: [51.0550, 3.7230], zoom: 15,
      spots: [
        s("gh-graslei", "Graslei & Korenlei", "photo", 51.0545, 3.7203, "Graslei, 9000 Gent, Belgium", "Graslei",
          "Golden hour and blue hour, when the guild houses light up", ["Sit on the quay edge with your legs over the water", "Walking shot along the Graslei facades"]),
        s("gh-st-michael-bridge", "Saint Michael's Bridge", "photo", 51.0539, 3.7197, "Sint-Michielsbrug, 9000 Gent, Belgium", "St._Michael's_Bridge,_Ghent",
          "Sunset: the famous view of Ghent's three towers", ["Stand at the railing with all three towers lined up behind you"]),
        s("gh-gravensteen", "Gravensteen Castle", "sight", 51.0573, 3.7208, "Sint-Veerleplein 11, 9000 Gent, Belgium", "Gravensteen",
          "Afternoon, from across the water", ["Full-length shot on the bridge with the castle walls behind"]),
        s("gh-st-bavo", "St Bavo's Cathedral", "sight", 51.0530, 3.7267, "Sint-Baafsplein, 9000 Gent, Belgium", "St_Bavo's_Cathedral,_Ghent",
          "Morning; see the Ghent Altarpiece inside", ["Looking up at the tower from the square"]),
        s("gh-belfry", "Belfry of Ghent", "sight", 51.0536, 3.7247, "Sint-Baafsplein, 9000 Gent, Belgium", "Belfry_of_Ghent",
          "Go up for the view at golden hour", ["City panorama from the top, you at the window edge"]),
        s("gh-graffiti", "Werregarenstraat (Graffiti Street)", "photo", 51.0551, 3.7244, "Werregarenstraat, 9000 Gent, Belgium", "Werregarenstraat",
          "Any time; the art changes constantly", ["Lean against the most colourful wall, outfit contrasting the paint"]),
        s("gh-patershol", "Patershol", "food", 51.0581, 3.7225, "Patershol, 9000 Gent, Belgium", "Patershol",
          "Dinner time, when the cobbled lanes are lit", ["Candid walking shot down the narrow lanes"]),
        s("gh-vrijdagmarkt", "Vrijdagmarkt", "sight", 51.0569, 3.7262, "Vrijdagmarkt, 9000 Gent, Belgium", "Vrijdagmarkt",
          "Friday market mornings", ["Wide shot of the colourful square with you in the centre"]),
      ],
    },
    {
      id: "paris", name: "Paris", center: [48.8600, 2.3200], zoom: 13,
      spots: [
        s("pa-trocadero", "Trocadéro (Eiffel Tower view)", "photo", 48.8616, 2.2893, "Place du Trocadéro, 75116 Paris, France", "Trocadéro",
          "Sunrise for an empty terrace; the tower sparkles on the hour after dark", ["Jump shot with the tower in the background", "Back to the camera, arms open toward the tower"]),
        s("pa-eiffel", "Eiffel Tower", "sight", 48.8584, 2.2945, "Champ de Mars, 5 Av. Anatole France, 75007 Paris, France", "Eiffel_Tower",
          "Golden hour from the Champ de Mars", ["Picnic flat-lay on the Champ de Mars lawn, tower behind"]),
        s("pa-bir-hakeim", "Pont de Bir-Hakeim", "photo", 48.8556, 2.2876, "Pont de Bir-Hakeim, 75015 Paris, France", "Pont_de_Bir-Hakeim",
          "Early morning, when the columns frame the tower", ["Walk between the iron columns, symmetrical shot down the middle"]),
        s("pa-louvre", "Louvre Pyramid", "sight", 48.8611, 2.3358, "Rue de Rivoli, 75001 Paris, France", "Louvre_Pyramid",
          "Blue hour, when the pyramid lights up", ["Forced-perspective shot 'touching' the pyramid tip", "Sit on the fountain edge with the pyramid behind"]),
        s("pa-palais-royal", "Palais-Royal Columns", "photo", 48.8635, 2.3370, "8 Rue de Montpensier, 75001 Paris, France", "Les_Deux_Plateaux",
          "Soft morning light", ["Stand on a striped column, shot from low"]),
        s("pa-alexandre-iii", "Pont Alexandre III", "photo", 48.8639, 2.3136, "Pont Alexandre III, 75008 Paris, France", "Pont_Alexandre_III",
          "Sunset, with the golden statues lit", ["Leaning on the ornate lamp post, Eiffel Tower in the distance"]),
        s("pa-arc", "Arc de Triomphe", "sight", 48.8738, 2.2950, "Place Charles de Gaulle, 75008 Paris, France", "Arc_de_Triomphe",
          "Sunset from the rooftop", ["Rooftop shot with the Champs-Élysées behind you"]),
        s("pa-sacre-coeur", "Sacré-Cœur", "sight", 48.8867, 2.3431, "35 Rue du Chevalier de la Barre, 75018 Paris, France", "Sacré-Cœur,_Paris",
          "Sunrise, with the city view from the steps", ["Sit on the steps with Paris spread out below"]),
        s("pa-consulat", "Le Consulat (Montmartre)", "food", 48.8866, 2.3404, "18 Rue Norvins, 75018 Paris, France", null,
          "Morning coffee", ["Coffee at a corner table with the café sign above you"]),
        s("pa-cremieux", "Rue Crémieux", "photo", 48.8461, 2.3714, "Rue Crémieux, 75012 Paris, France", "Rue_Crémieux",
          "Weekday mornings; residents ask visitors to be quiet", ["Walking past the pastel houses, candid"]),
        s("pa-flore", "Café de Flore", "food", 48.8541, 2.3326, "172 Bd Saint-Germain, 75006 Paris, France", "Café_de_Flore",
          "Late morning on the terrace", ["Croissant and coffee shot at a terrace table"]),
        s("pa-shakespeare", "Shakespeare and Company", "shop", 48.8526, 2.3471, "37 Rue de la Bûcherie, 75005 Paris, France", "Shakespeare_and_Company_(bookstore)",
          "Opening time; no photos inside", ["Browsing the green book stalls outside"]),
      ],
    },
    {
      id: "amsterdam", name: "Amsterdam", center: [52.3690, 4.8930], zoom: 14,
      spots: [
        s("am-rijksmuseum", "Rijksmuseum", "sight", 52.3600, 4.8852, "Museumstraat 1, 1071 XX Amsterdam, Netherlands", "Rijksmuseum",
          "Morning, before it opens", ["Cycle or walk through the passage under the museum"]),
        s("am-reguliersgracht", "Reguliersgracht (Seven Bridges)", "photo", 52.3632, 4.8961, "Reguliersgracht, 1017 Amsterdam, Netherlands", "Reguliersgracht",
          "Blue hour, when the bridges light up", ["Stand on the bridge so the row of arches lines up behind you"]),
        s("am-magere-brug", "Magere Brug", "photo", 52.3634, 4.9025, "Kerkstraat, 1017 GM Amsterdam, Netherlands", "Magere_Brug",
          "After dark, when it's lit with bulbs", ["Walking across with the lights glowing behind"]),
        s("am-bloemgracht", "Bloemgracht (Jordaan)", "photo", 52.3743, 4.8817, "Bloemgracht, 1016 Amsterdam, Netherlands", "Bloemgracht",
          "Morning; bikes and flowers everywhere", ["Holding a bike by the canal railing", "Sitting on a canal house stoop"]),
        s("am-anne-frank", "Anne Frank House", "sight", 52.3752, 4.8840, "Westermarkt 20, 1016 GV Amsterdam, Netherlands", "Anne_Frank_House",
          "Book tickets weeks ahead; be respectful", []),
        s("am-bloemenmarkt", "Bloemenmarkt", "shop", 52.3667, 4.8916, "Singel, 1012 DH Amsterdam, Netherlands", "Bloemenmarkt",
          "Spring for fresh tulips", ["Holding a tulip bunch in front of the stalls"]),
        s("am-dam", "Dam Square & Royal Palace", "sight", 52.3731, 4.8926, "Dam, 1012 JS Amsterdam, Netherlands", "Royal_Palace_of_Amsterdam",
          "Early morning", ["Wide shot with the palace facade behind you"]),
        s("am-dancing-houses", "Dancing Houses (Damrak)", "photo", 52.3757, 4.8966, "Damrak, 1012 Amsterdam, Netherlands", "Damrak",
          "Golden hour from across the water", ["Tilted-house shot from the water's edge"]),
        s("am-vondelpark", "Vondelpark", "photo", 52.3580, 4.8686, "Vondelpark, 1071 AA Amsterdam, Netherlands", "Vondelpark",
          "Autumn mornings", ["Cycling down the tree-lined path"]),
        s("am-adam", "A'DAM Lookout", "photo", 52.3843, 4.9019, "Overhoeksplein 5, 1031 KS Amsterdam, Netherlands", "A'DAM_Toren",
          "Sunset over the IJ", ["Over-the-edge swing shot", "City panorama from the rooftop"]),
        s("am-smalle", "Café 't Smalle", "food", 52.3770, 4.8833, "Egelantiersgracht 12, 1015 RL Amsterdam, Netherlands", null,
          "Late afternoon on the canal-side terrace", ["Drinks on the tiny canal terrace"]),
      ],
    },
    {
      id: "luxembourg", name: "Luxembourg", center: [49.6110, 6.1330], zoom: 15,
      spots: [
        s("lu-corniche", "Chemin de la Corniche", "photo", 49.6111, 6.1365, "Chemin de la Corniche, 1945 Luxembourg", "Chemin_de_la_Corniche",
          "Morning light over the Grund", ["Leaning on the wall with the Grund valley behind you"]),
        s("lu-grund", "Grund & Neumünster Abbey", "photo", 49.6097, 6.1373, "28 Rue Münster, 2160 Luxembourg", "Neumünster_Abbey",
          "Late afternoon by the Alzette river", ["Walking on the riverside path with the abbey behind", "Sitting on the little stone bridge"]),
        s("lu-bock", "Bock Casemates", "sight", 49.6117, 6.1373, "10 Mont Saint-Michel, 1222 Luxembourg", "Casemates_du_Bock",
          "Midday; windows frame the valley", ["Silhouette in a stone window opening"]),
        s("lu-palace", "Grand Ducal Palace", "sight", 49.6112, 6.1323, "17 Rue du Marché-aux-Herbes, 1728 Luxembourg", "Grand_Ducal_Palace,_Luxembourg",
          "Morning, before the guard change", ["Symmetrical shot in front of the facade"]),
        s("lu-cathedral", "Notre-Dame Cathedral", "sight", 49.6097, 6.1315, "Rue Notre Dame, 2240 Luxembourg", "Notre-Dame_Cathedral,_Luxembourg",
          "Afternoon", ["Looking up at the spires from the side street"]),
        s("lu-adolphe", "Adolphe Bridge", "photo", 49.6075, 6.1280, "Pont Adolphe, Luxembourg", "Adolphe_Bridge",
          "Sunset from the Pétrusse valley", ["Shot from the valley below with the arch above you"]),
        s("lu-guillaume", "Place Guillaume II", "sight", 49.6107, 6.1305, "Place Guillaume II, 1648 Luxembourg", "Place_Guillaume_II",
          "Market mornings (Wednesday and Saturday)", ["Walking past the market stalls"]),
        s("lu-pfaffenthal", "Pfaffenthal Panoramic Lift", "photo", 49.6141, 6.1308, "Rue du Pont, 2344 Luxembourg", "Pfaffenthal_Panoramic_Elevator",
          "Golden hour", ["Glass-floor shot looking down", "Valley view from the top platform"]),
        s("lu-place-armes", "Place d'Armes", "food", 49.6115, 6.1294, "Place d'Armes, 1136 Luxembourg", "Place_d'Armes,_Luxembourg",
          "Evening terraces", ["Café table shot under the trees"]),
      ],
    },
  ];
})();

// "Paris weekend": the Saturday + Sunday plan from Graciella's itinerary,
// copied row by row. Each stop has its planned time (`at`), visit length
// (`stay`, minutes, 0 = walk-by), how you get there (`via`, as written in
// the itinerary) and the note. `ref` reuses a ready-made Paris spot.
(() => {
  // "5 min walk", "20 min Metro", "1 hr 45 mins" → minutes.
  const mins = (t) => (Number((/(\d+)\s*hr/.exec(t) || [])[1] || 0) * 60) + Number((/(\d+)\s*min/.exec(t) || [])[1] || 0);
  const via = (how, extra = {}) => (how === "-" ? { how: "", mins: 0, ...extra } : { how, mins: mins(how), ...extra });
  const p = (at, stay, how, id, name, category, lat, lng, address, note, wiki = null) =>
    ({ at, stay, via: via(how), id, name, category, lat, lng, address, note, wiki, poses: [] });
  const ref = (at, stay, how, id, name, note) => ({ at, stay, via: via(how), ref: id, name, note });
  const day1 = [
    p("15:35", 5, "5 min walk", "pw-garnier", "Opéra Garnier (Exterior)", "sight", 48.8720, 2.3316, "Place de l'Opéra, 75009 Paris, France", "Exterior photos only.", "Palais_Garnier"),
    p("16:00", 30, "-", "pw-soubise", "National Archives / Hôtel de Soubise", "sight", 48.8597, 2.3575, "60 Rue des Francs-Bourgeois, 75003 Paris, France", "Free interior access; closes at 17:30.", "Hôtel_de_Soubise"),
    p("16:30", 5, "5 min walk", "pw-lamoignon", "Hôtel de Lamoignon", "photo", 48.8571, 2.3611, "24 Rue Pavée, 75004 Paris, France", "Quick courtyard photo.", "Hôtel_Lamoignon"),
    p("16:40", 5, "5 min walk", "pw-carnavalet", "Carnavalet (Exterior)", "sight", 48.8575, 2.3625, "23 Rue de Sévigné, 75003 Paris, France", "Exterior photo stop.", "Musée_Carnavalet"),
    p("16:50", 10, "5 min walk", "pw-vosges", "Place des Vosges", "photo", 48.8556, 2.3655, "Place des Vosges, 75004 Paris, France", "Free square and arcades.", "Place_des_Vosges"),
    p("17:05", 5, "5 min walk", "pw-sully", "Hôtel de Sully", "photo", 48.8545, 2.3640, "62 Rue Saint-Antoine, 75004 Paris, France", "Quick exterior/courtyard photo stop.", "Hôtel_de_Sully"),
    p("17:45", 5, "-", "pw-pantheon", "Panthéon (Exterior)", "sight", 48.8462, 2.3464, "Place du Panthéon, 75005 Paris, France", "Quick exterior photo.", "Panthéon"),
    p("17:50", 45, "10 min walk", "pw-luxembourg", "Luxembourg Garden", "photo", 48.8462, 2.3372, "Jardin du Luxembourg, 75006 Paris, France", "Enjoy the gardens before the 18:45 closure.", "Jardin_du_Luxembourg"),
    p("18:45", 5, "5 min walk", "pw-sorbonne", "Le Choupinet & Sorbonne", "photo", 48.8487, 2.3431, "Place de la Sorbonne, 75005 Paris, France", "Quick exterior photo.", "University_of_Paris"),
    p("18:55", 5, "5 min walk", "pw-cluny", "Musée de Cluny (Exterior)", "sight", 48.8506, 2.3440, "28 Rue du Sommerard, 75005 Paris, France", "Quick exterior photo.", "Musée_de_Cluny"),
    p("19:05", 5, "5 min walk", "pw-st-michel", "Fontaine Saint-Michel & Huchette", "photo", 48.8533, 2.3437, "Place Saint-Michel, 75005 Paris, France", "Quick photo stop.", "Fontaine_Saint-Michel"),
    ref("19:15", 10, "5 min walk", "pa-shakespeare", "Shakespeare & Company", "Free browsing."),
    p("19:30", 15, "5 min walk", "pw-notre-dame", "Notre-Dame (Exterior)", "sight", 48.8530, 2.3499, "6 Parvis Notre-Dame, 75004 Paris, France", "Extended exterior visit.", "Notre-Dame_de_Paris"),
    p("19:50", 5, "10 min walk", "pw-conciergerie", "Palais de Justice & Conciergerie", "sight", 48.8560, 2.3455, "2 Bd du Palais, 75001 Paris, France", "Quick exterior photo.", "Conciergerie"),
    p("20:05", 5, "5 min walk", "pw-pont-neuf", "Henri IV Statue & Pont Neuf", "photo", 48.8572, 2.3409, "Pont Neuf, 75001 Paris, France", "Quick photo stop next to the pier.", "Pont_Neuf"),
    p("20:15", 30, "-", "pw-dinner", "Dinner / Takeaway", "food", 48.8566, 2.3423, "Place Dauphine, 75001 Paris, France", "Grab food nearby before checking in for the cruise."),
    p("20:45", 105, "-", "pw-cruise", "Seine Cruise (Vedettes du Pont Neuf)", "sight", 48.8577, 2.3397, "Square du Vert-Galant, 75001 Paris, France", "Arrive by 20:45 for the 21:15 departure."),
  ];
  // The two travel rows of Saturday belong to the stop they lead to.
  day1[1].via = via("20 min Metro", { at: "15:40", label: "Metro to the Marais", note: "Take the metro to the Archives area." });
  day1[6].via = via("30 min walk", { at: "17:15", label: "Transit Walk: The Left Bank",
    note: "Brisk walk passing Saint-Paul-Saint-Louis, Pont de Sully, Arab World Institute, and Saint-Étienne-du-Mont." });
  const day2 = [
    p("08:35", 0, "5 min walk", "pw-cour-rome", "Gare Saint-Lazare - Cour de Rome", "photo", 48.8758, 2.3245, "Cour de Rome, 75008 Paris, France", "Quick photo without stopping.", "Gare_Saint-Lazare"),
    p("08:45", 0, "10 min walk", "pw-augustin", "Église Saint-Augustin", "sight", 48.8758, 2.3184, "46 Bd Malesherbes, 75008 Paris, France", "Quick exterior photo on the move.", "Saint-Augustin,_Paris"),
    p("09:00", 30, "15 min walk", "pw-monceau", "Parc Monceau", "photo", 48.8797, 2.3091, "35 Bd de Courcelles, 75008 Paris, France", "Dedicated time for a morning stroll.", "Parc_Monceau"),
    p("09:35", 0, "5 min walk", "pw-nevsky", "Cathedrale Saint Alexandre Nevsky", "sight", 48.8780, 2.3017, "12 Rue Daru, 75008 Paris, France", "Quick photo as you pass.", "Alexander_Nevsky_Cathedral,_Paris"),
    ref("09:45", 15, "10 min walk", "pa-arc", "Arc de Triomphe", "View from the crosswalks and base."),
    p("10:05", 0, "5 min walk", "pw-133-champs", "133 Av. des Champs-Élysées", "photo", 48.8730, 2.2990, "133 Av. des Champs-Élysées, 75008 Paris, France", "Snap a photo while walking down the avenue."),
    p("10:15", 0, "10 min walk", "pw-etats-unis", "Place des États-Unis & Baccarat", "photo", 48.8677, 2.2917, "Place des États-Unis, 75116 Paris, France", "Continuous walking photo.", "Place_des_États-Unis"),
    p("10:20", 0, "5 min walk", "pw-guimet", "Musée Guimet", "sight", 48.8652, 2.2936, "6 Place d'Iéna, 75116 Paris, France", "Continuous walking photo.", "Musée_Guimet"),
    ref("10:30", 10, "10 min walk", "pa-trocadero", "Palais de Chaillot & Trocadéro", "Stop for the iconic elevated Eiffel Tower view."),
    ref("10:55", 20, "15 min walk", "pa-eiffel", "Eiffel Tower (Free Esplanade)", "Walk under and around the base."),
    p("11:20", 5, "5 min walk", "pw-universite", "Rue de l'Université", "photo", 48.8590, 2.3018, "Rue de l'Université, 75007 Paris, France", "Stop for the classic street-level view."),
    p("11:30", 0, "5 min walk", "pw-branly", "Musée du quai Branly", "sight", 48.8609, 2.2977, "37 Quai Branly, 75007 Paris, France", "View the exterior green wall as you walk.", "Musée_du_quai_Branly_–_Jacques_Chirac"),
    p("11:35", 0, "5 min walk", "pw-trinite", "Cathédrale de la Sainte-Trinité", "sight", 48.8620, 2.3015, "1 Quai Branly, 75007 Paris, France", "Quick photo of the domes.", "Holy_Trinity_Cathedral,_Paris"),
    p("11:45", 0, "10 min walk", "pw-invalides-bridge", "Quai d'Orsay & Pont des Invalides", "photo", 48.8628, 2.3103, "Quai d'Orsay, 75007 Paris, France", "Riverside walk.", "Pont_des_Invalides"),
    ref("11:50", 5, "5 min walk", "pa-alexandre-iii", "Pont Alexandre III", "Brief stop to appreciate the bridge details."),
    p("12:00", 0, "5 min walk", "pw-palais", "Grand Palais & Petit Palais", "sight", 48.8661, 2.3125, "Av. Winston Churchill, 75008 Paris, France", "Exterior photos while walking past.", "Grand_Palais"),
    p("12:10", 0, "10 min walk", "pw-concorde", "Place de la Concorde", "sight", 48.8656, 2.3212, "Place de la Concorde, 75008 Paris, France", "View the Obelisk and fountain while crossing.", "Place_de_la_Concorde"),
    p("12:15", 10, "5 min walk", "pw-tuileries", "Jardin des Tuileries & Grand Bassin", "photo", 48.8634, 2.3275, "Jardin des Tuileries, 75001 Paris, France", "Brisk pace through the main garden path.", "Tuileries_Garden"),
    p("12:35", 0, "10 min walk", "pw-carrousel", "Arc de Triomphe du Carrousel", "photo", 48.8617, 2.3329, "Place du Carrousel, 75001 Paris, France", "Quick photo.", "Arc_de_Triomphe_du_Carrousel"),
    ref("12:40", 10, "5 min walk", "pa-louvre", "Louvre (Courtyard/Pyramid)", "Photo stop at the glass pyramids."),
    ref("13:00", 5, "10 min walk", "pa-palais-royal", "Palais Royal & Colonnes de Buren", "Stop at the striped columns."),
    p("13:10", 5, "5 min walk", "pw-vivienne", "Galerie Vivienne", "photo", 48.8664, 2.3399, "4 Rue des Petits Champs, 75002 Paris, France", "Walk through the covered passage.", "Galerie_Vivienne"),
    p("13:30", 25, "15 min walk", "pw-lafayette", "Galeries Lafayette & Rooftop", "shop", 48.8738, 2.3320, "40 Bd Haussmann, 75009 Paris, France", "View the dome interior and rooftop views, grab a snack.", "Galeries_Lafayette"),
    p("14:00", 29, "5 min walk", "pw-hotel", "Residhome Paris Opéra", "stay", 48.8750, 2.3296, "30 Rue Joubert, 75009 Paris, France", "Arrive at the hotel to grab your luggage and prepare to leave."),
  ];
  window.SEED_PARIS_WEEKEND = {
    version: 2,
    start: { name: "Residhome Paris Opéra", lat: 48.8750, lng: 2.3296 },
    names: ["Saturday", "Sunday"],
    titles: ["The Marais, Latin Quarter & Seine Walk", "West Paris, Eiffel Tower & Louvre"],
    blurbs: [
      "This route relies on a brisk walking pace between stops to ensure you reach the Luxembourg Garden before it closes and make your evening cruise.",
      "This route features \"walk-by\" sightseeing for minor monuments to ensure you get dedicated time at Parc Monceau, the Eiffel Tower, and Galeries Lafayette before your afternoon departure.",
    ],
    departs: ["Depart hotel.", "Depart hotel."],
    finish: [null, { at: "14:29", name: "Departure", note: "Leave hotel to catch Metro 12." }],
    hours: [{ start: "15:30", end: "22:30" }, { start: "08:30", end: "14:29" }],
    // Pins from the first version that aren't rows in the itinerary.
    removed: ["pw-st-paul", "pw-pont-sully", "pw-ima", "pw-st-etienne"],
    days: [day1, day2],
  };
})();
