// Seed data: Brussels, matching the "Brussels in One Day" map.
// `wiki` is an English Wikipedia page title used to fetch a cover photo.
// `poses` are shot ideas shown in the sidebar for each spot.
window.SEED_CITY = {
  name: "Brussels",
  center: [50.8466, 4.3540],
  zoom: 15,
};

window.CATEGORIES = {
  sight: { label: "Sight", color: "#2a7de1", emoji: "🏛️" },
  photo: { label: "Photo spot", color: "#9b2fae", emoji: "📸" },
  food: { label: "Food & drink", color: "#f2b705", emoji: "🧇" },
  shop: { label: "Shopping", color: "#1e9e6a", emoji: "🛍️" },
  stay: { label: "Hotel", color: "#e04848", emoji: "🛏️" },
};

window.SEED_SPOTS = [
  {
    id: "grand-place",
    name: "Grand-Place",
    category: "sight",
    lat: 50.8467, lng: 4.3525,
    address: "Grand-Place, 1000 Bruxelles, Belgium",
    wiki: "Grand-Place",
    bestTime: "Before 9am for an empty square; blue hour for the lit-up facades",
    poses: [
      "Walk toward the camera with the Town Hall tower centred behind you",
      "Sit on the cobblestones, shot from low, with the gilded guildhalls filling the frame",
      "Over-the-shoulder look back from the corner by Rue au Beurre",
    ],
  },
  {
    id: "galeries",
    name: "Galeries Royales Saint-Hubert",
    category: "shop",
    lat: 50.8478, lng: 4.3548,
    address: "Galerie du Roi 5, 1000 Bruxelles, Belgium",
    wiki: "Royal_Galleries_of_Saint-Hubert",
    bestTime: "Early morning, before the shops open",
    poses: [
      "Stand in the centre of the arcade so the glass roof lines lead to you",
      "Candid shot window-shopping at a chocolatier",
    ],
  },
  {
    id: "manneken-pis",
    name: "Manneken Pis",
    category: "sight",
    lat: 50.8450, lng: 4.3500,
    address: "Rue de l'Étuve 46, 1000 Bruxelles, Belgium",
    wiki: "Manneken_Pis",
    bestTime: "Check the costume calendar, as he is dressed up most weeks",
    poses: ["Playful mirror pose beside the fountain (it's tiny, so stand close)"],
  },
  {
    id: "dandoy",
    name: "Maison Dandoy (waffles)",
    category: "food",
    lat: 50.8476, lng: 4.3517,
    address: "Rue au Beurre 31, 1000 Bruxelles, Belgium",
    wiki: "Maison_Dandoy",
    bestTime: "Mid-afternoon to skip the queue",
    poses: [
      "Waffle held up in the foreground with the storefront blurred behind",
      "Flat-lay of waffle and coffee on the table",
    ],
  },
  {
    id: "delirium",
    name: "Delirium Café",
    category: "food",
    lat: 50.8486, lng: 4.3537,
    address: "Impasse de la Fidélité 4, 1000 Bruxelles, Belgium",
    wiki: "Delirium_Café",
    bestTime: "Evening, when the alley lights are on",
    poses: ["Cheers shot in the lantern-lit alley"],
  },
  {
    id: "cathedral",
    name: "St. Michael and St. Gudula Cathedral",
    category: "sight",
    lat: 50.8478, lng: 4.3600,
    address: "Place Sainte-Gudule, 1000 Bruxelles, Belgium",
    wiki: "St._Michael_and_St._Gudula_Cathedral",
    bestTime: "Late afternoon sun on the facade",
    poses: ["Sit halfway up the front steps, shot from the bottom looking up"],
  },
  {
    id: "comic-center",
    name: "Centre Belge de la Bande Dessinée",
    category: "photo",
    lat: 50.8510, lng: 4.3594,
    address: "Rue des Sables 20, 1000 Bruxelles, Belgium",
    wiki: "Belgian_Comic_Strip_Center",
    bestTime: "Any time; the Art Nouveau hall has soft daylight",
    poses: ["Pose next to the giant Tintin rocket in the entrance hall"],
  },
  {
    id: "bozar",
    name: "BOZAR",
    category: "sight",
    lat: 50.8441, lng: 4.3597,
    address: "Rue Ravenstein 23, 1000 Bruxelles, Belgium",
    phone: "+32 2 507 82 00",
    website: "https://www.bozar.be",
    wiki: "Centre_for_Fine_Arts,_Brussels",
    bestTime: "Golden hour on the Art Deco exterior",
    poses: ["Walking past the curved facade, shot from across Rue Ravenstein"],
  },
  {
    id: "mim",
    name: "Musical Instruments Museum (Old England)",
    category: "photo",
    lat: 50.8429, lng: 4.3582,
    address: "Rue Montagne de la Cour 2, 1000 Bruxelles, Belgium",
    wiki: "Musical_Instruments_Museum_(Brussels)",
    bestTime: "Morning, when the light is soft on the ironwork",
    poses: [
      "Full-length shot in front of the Art Nouveau iron facade",
      "Rooftop café shot with the city skyline behind you",
    ],
  },
  {
    id: "mont-des-arts",
    name: "Mont des Arts",
    category: "photo",
    lat: 50.8437, lng: 4.3565,
    address: "Mont des Arts, 1000 Bruxelles, Belgium",
    wiki: "Mont_des_Arts",
    bestTime: "Sunset, looking down toward the Town Hall spire",
    poses: [
      "Back to the camera at the top of the stairs, looking out over the garden to the spire",
      "Sitting on the garden wall with the hedges forming leading lines",
      "Twirl shot in the middle of the stairs",
    ],
  },
  {
    id: "fine-arts",
    name: "Musées Royaux des Beaux-Arts",
    category: "sight",
    lat: 50.8418, lng: 4.3580,
    address: "Rue de la Régence 3, 1000 Bruxelles, Belgium",
    wiki: "Royal_Museums_of_Fine_Arts_of_Belgium",
    bestTime: "Weekday mornings are quietest",
    poses: ["Silhouette in front of a large canvas (check the photo rules first)"],
  },
  {
    id: "parc",
    name: "Parc de Bruxelles",
    category: "photo",
    lat: 50.8448, lng: 4.3640,
    address: "Rue Royale, 1000 Bruxelles, Belgium",
    wiki: "Brussels_Park",
    bestTime: "Autumn leaves, mid-morning",
    poses: ["Walking down the tree-lined central alley toward the Palace"],
  },
  {
    id: "palace",
    name: "Royal Palace of Brussels",
    category: "sight",
    lat: 50.8417, lng: 4.3620,
    address: "Rue Brederode 16, 1000 Bruxelles, Belgium",
    wiki: "Royal_Palace_of_Brussels",
    bestTime: "Open to visitors in summer only; facade any time",
    poses: ["Symmetrical centred shot through the gates"],
  },
  {
    id: "sablon",
    name: "Place du Grand Sablon",
    category: "food",
    lat: 50.8400, lng: 4.3555,
    address: "Place du Grand Sablon, 1000 Bruxelles, Belgium",
    wiki: "Place_du_Grand_Sablon",
    bestTime: "Weekend antiques market mornings",
    poses: ["Chocolate-shop window shot (Pierre Marcolini, Wittamer)"],
  },
  {
    id: "notre-dame-sablon",
    name: "Notre-Dame du Sablon",
    category: "photo",
    lat: 50.8397, lng: 4.3568,
    address: "Rue de la Régence 3B, 1000 Bruxelles, Belgium",
    wiki: "Church_of_Our_Blessed_Lady_of_the_Sablon",
    bestTime: "Sunny afternoons, when the stained glass glows inside",
    poses: ["Standing in the Gothic doorway, looking up"],
  },
  {
    id: "poelaert",
    name: "Grande Roue / Place Poelaert",
    category: "photo",
    lat: 50.8375, lng: 4.3527,
    address: "Place Poelaert, 1000 Bruxelles, Belgium",
    wiki: "Palace_of_Justice,_Brussels",
    bestTime: "Sunset, for the panorama over the Marolles",
    poses: ["Leaning on the railing with the city skyline behind you"],
  },
];
