// Seed data: Brussels, matching the "Brussels in One Day" map.
// `wiki` is an English Wikipedia page title used to fetch a cover photo.
// `poses` are shot ideas shown in the sidebar for each spot.
window.SEED_CITY = {
  name: "Brussels",
  center: [50.8466, 4.3540],
  zoom: 15,
};

window.CATEGORIES = {
  sight: { label: "Sight", color: "#007AFF", emoji: "🏛️" },
  photo: { label: "Photo spot", color: "#AF52DE", emoji: "📸" },
  food: { label: "Food & drink", color: "#FF9500", emoji: "🧇" },
  shop: { label: "Shopping", color: "#34C759", emoji: "🛍️" },
  stay: { label: "Hotel", color: "#FF3B30", emoji: "🛏️" },
};

window.SEED_SPOTS = [
  {
    id: "grand-place",
    name: "Grand-Place",
    category: "sight",
    lat: 50.8467, lng: 4.3525,
    address: "Grand-Place, 1000 Bruxelles, Belgium",
    wiki: "Grand-Place",
    bestTime: "Before 9am for an empty square; blue hour for the lit-up facades",
    poses: [
      "Walk toward the camera with the Town Hall tower centred behind you",
      "Sit on the cobblestones, shot from low, with the gilded guildhalls filling the frame",
      "Over-the-shoulder look back from the corner by Rue au Beurre",
    ],
  },
  {
    id: "galeries",
    name: "Galeries Royales Saint-Hubert",
    category: "shop",
    lat: 50.8478, lng: 4.3548,
    address: "Galerie du Roi 5, 1000 Bruxelles, Belgium",
    wiki: "Royal_Galleries_of_Saint-Hubert",
    bestTime: "Early morning, before the shops open",
    poses: [
      "Stand in the centre of the arcade so the glass roof lines lead to you",
      "Candid shot window-shopping at a chocolatier",
    ],
  },
  {
    id: "manneken-pis",
    name: "Manneken Pis",
    category: "sight",
    lat: 50.8450, lng: 4.3500,
    address: "Rue de l'Étuve 46, 1000 Bruxelles, Belgium",
    wiki: "Manneken_Pis",
    bestTime: "Check the costume calendar, as he is dressed up most weeks",
    poses: ["Playful mirror pose beside the fountain (it's tiny, so stand close)"],
  },
  {
    id: "dandoy",
    name: "Maison Dandoy (waffles)",
    category: "food",
    lat: 50.8476, lng: 4.3517,
    address: "Rue au Beurre 31, 1000 Bruxelles, Belgium",
    wiki: "Maison_Dandoy",
    bestTime: "Mid-afternoon to skip the queue",
    poses: [
      "Waffle held up in the foreground with the storefront blurred behind",
      "Flat-lay of waffle and coffee on the table",
    ],
  },
  {
    id: "delirium",
    name: "Delirium Café",
    category: "food",
    lat: 50.8486, lng: 4.3537,
    address: "Impasse de la Fidélité 4, 1000 Bruxelles, Belgium",
    wiki: "Delirium_Café",
    bestTime: "Evening, when the alley lights are on",
    poses: ["Cheers shot in the lantern-lit alley"],
  },
  {
    id: "cathedral",
    name: "St. Michael and St. Gudula Cathedral",
    category: "sight",
    lat: 50.8478, lng: 4.3600,
    address: "Place Sainte-Gudule, 1000 Bruxelles, Belgium",
    wiki: "St._Michael_and_St._Gudula_Cathedral",
    bestTime: "Late afternoon sun on the facade",
    poses: ["Sit halfway up the front steps, shot from the bottom looking up"],
  },
  {
    id: "comic-center",
    name: "Centre Belge de la Bande Dessinée",
    category: "photo",
    lat: 50.8510, lng: 4.3594,
    address: "Rue des Sables 20, 1000 Bruxelles, Belgium",
    wiki: "Belgian_Comic_Strip_Center",
    bestTime: "Any time; the Art Nouveau hall has soft daylight",
    poses: ["Pose next to the giant Tintin rocket in the entrance hall"],
  },
  {
    id: "bozar",
    name: "BOZAR",
    category: "sight",
    lat: 50.8441, lng: 4.3597,
    address: "Rue Ravenstein 23, 1000 Bruxelles, Belgium",
    phone: "+32 2 507 82 00",
    website: "https://www.bozar.be",
    wiki: "Centre_for_Fine_Arts,_Brussels",
    bestTime: "Golden hour on the Art Deco exterior",
    poses: ["Walking past the curved facade, shot from across Rue Ravenstein"],
  },
  {
    id: "mim",
    name: "Musical Instruments Museum (Old England)",
    category: "photo",
    lat: 50.8429, lng: 4.3582,
    address: "Rue Montagne de la Cour 2, 1000 Bruxelles, Belgium",
    wiki: "Musical_Instruments_Museum_(Brussels)",
    bestTime: "Morning, when the light is soft on the ironwork",
    poses: [
      "Full-length shot in front of the Art Nouveau iron facade",
      "Rooftop café shot with the city skyline behind you",
    ],
  },
  {
    id: "mont-des-arts",
    name: "Mont des Arts",
    category: "photo",
    lat: 50.8437, lng: 4.3565,
    address: "Mont des Arts, 1000 Bruxelles, Belgium",
    wiki: "Mont_des_Arts",
    bestTime: "Sunset, looking down toward the Town Hall spire",
    poses: [
      "Back to the camera at the top of the stairs, looking out over the garden to the spire",
      "Sitting on the garden wall with the hedges forming leading lines",
      "Twirl shot in the middle of the stairs",
    ],
  },
  {
    id: "fine-arts",
    name: "Musées Royaux des Beaux-Arts",
    category: "sight",
    lat: 50.8418, lng: 4.3580,
    address: "Rue de la Régence 3, 1000 Bruxelles, Belgium",
    wiki: "Royal_Museums_of_Fine_Arts_of_Belgium",
    bestTime: "Weekday mornings are quietest",
    poses: ["Silhouette in front of a large canvas (check the photo rules first)"],
  },
  {
    id: "parc",
    name: "Parc de Bruxelles",
    category: "photo",
    lat: 50.8448, lng: 4.3640,
    address: "Rue Royale, 1000 Bruxelles, Belgium",
    wiki: "Brussels_Park",
    bestTime: "Autumn leaves, mid-morning",
    poses: ["Walking down the tree-lined central alley toward the Palace"],
  },
  {
    id: "palace",
    name: "Royal Palace of Brussels",
    category: "sight",
    lat: 50.8417, lng: 4.3620,
    address: "Rue Brederode 16, 1000 Bruxelles, Belgium",
    wiki: "Royal_Palace_of_Brussels",
    bestTime: "Open to visitors in summer only; facade any time",
    poses: ["Symmetrical centred shot through the gates"],
  },
  {
    id: "sablon",
    name: "Place du Grand Sablon",
    category: "food",
    lat: 50.8400, lng: 4.3555,
    address: "Place du Grand Sablon, 1000 Bruxelles, Belgium",
    wiki: "Place_du_Grand_Sablon",
    bestTime: "Weekend antiques market mornings",
    poses: ["Chocolate-shop window shot (Pierre Marcolini, Wittamer)"],
  },
  {
    id: "notre-dame-sablon",
    name: "Notre-Dame du Sablon",
    category: "photo",
    lat: 50.8397, lng: 4.3568,
    address: "Rue de la Régence 3B, 1000 Bruxelles, Belgium",
    wiki: "Church_of_Our_Blessed_Lady_of_the_Sablon",
    bestTime: "Sunny afternoons, when the stained glass glows inside",
    poses: ["Standing in the Gothic doorway, looking up"],
  },
  {
    id: "poelaert",
    name: "Grande Roue / Place Poelaert",
    category: "photo",
    lat: 50.8375, lng: 4.3527,
    address: "Place Poelaert, 1000 Bruxelles, Belgium",
    wiki: "Palace_of_Justice,_Brussels",
    bestTime: "Sunset, for the panorama over the Marolles",
    poses: ["Leaning on the railing with the city skyline behind you"],
  },
];

// More ready-made trips. Spot ids are prefixed per city so photos never mix.
(() => {
  const s = (id, name, category, lat, lng, address, wiki, bestTime, poses) =>
    ({ id, name, category, lat, lng, address, wiki, bestTime, poses });

  window.SEED_TRIPS = [
    {
      id: "bruges", name: "Bruges", center: [51.2070, 3.2260], zoom: 15,
      spots: [
        s("bg-markt", "Markt & Belfry", "sight", 51.2088, 3.2244, "Markt, 8000 Brugge, Belgium", "Belfry_of_Bruges",
          "Early morning before the tour groups; the colourful guild houses glow at sunset",
          ["Walk across the square with the Belfry tower behind you", "Sit by the horse carriages, shot from low"]),
        s("bg-rozenhoedkaai", "Rozenhoedkaai", "photo", 51.2073, 3.2275, "Rozenhoedkaai, 8000 Brugge, Belgium", "Rozenhoedkaai",
          "Blue hour, when the Belfry lights reflect in the canal",
          ["Lean on the canal wall, looking back over your shoulder, Belfry framed behind you", "Wide 0.5x shot with the canal leading to you"]),
        s("bg-burg", "Burg Square & City Hall", "sight", 51.2083, 3.2270, "Burg, 8000 Brugge, Belgium", "Bruges_City_Hall",
          "Golden hour on the Gothic facade", ["Symmetrical shot in front of the City Hall doors"]),
        s("bg-holy-blood", "Basilica of the Holy Blood", "sight", 51.2081, 3.2263, "Burg 13, 8000 Brugge, Belgium", "Basilica_of_the_Holy_Blood",
          "Late morning", ["Standing in the ornate gilded doorway"]),
        s("bg-bonifacius", "Bonifacius Bridge", "photo", 51.2049, 3.2253, "Groeninge, 8000 Brugge, Belgium", null,
          "Morning, before the crowds", ["Sit on the little stone bridge with the ivy-covered houses behind"]),
        s("bg-our-lady", "Church of Our Lady", "sight", 51.2048, 3.2245, "Mariastraat, 8000 Brugge, Belgium", "Church_of_Our_Lady,_Bruges",
          "Weekday mornings", ["Look up at the brick spire from the garden side"]),
        s("bg-begijnhof", "Begijnhof", "photo", 51.2002, 3.2235, "Begijnhof 24, 8000 Brugge, Belgium", "Princely_Beguinage_Ten_Wijngaerde",
          "April for the daffodils; keep quiet, it's a peaceful courtyard", ["Walking along the white houses under the trees"]),
        s("bg-minnewater", "Minnewater (Lake of Love)", "photo", 51.1990, 3.2252, "Minnewater, 8000 Brugge, Belgium", "Minnewater",
          "Sunrise, with mist on the water", ["Romantic over-the-shoulder look on the bridge", "Swans in the foreground, you in the background"]),
        s("bg-halve-maan", "De Halve Maan Brewery", "food", 51.2032, 3.2245, "Walplein 26, 8000 Brugge, Belgium", "De_Halve_Maan_Brewery",
          "Afternoon terrace", ["Cheers with a Brugse Zot on the terrace"]),
        s("bg-windmills", "Kruisvest Windmills", "photo", 51.2142, 3.2364, "Kruisvest, 8000 Brugge, Belgium", null,
          "Sunset, when the windmills are backlit", ["Walking along the path with a windmill on the hill behind you"]),
      ],
    },
    {
      id: "ghent", name: "Ghent", center: [51.0550, 3.7230], zoom: 15,
      spots: [
        s("gh-graslei", "Graslei & Korenlei", "photo", 51.0545, 3.7203, "Graslei, 9000 Gent, Belgium", "Graslei",
          "Golden hour and blue hour, when the guild houses light up", ["Sit on the quay edge with your legs over the water", "Walking shot along the Graslei facades"]),
        s("gh-st-michael-bridge", "Saint Michael's Bridge", "photo", 51.0539, 3.7197, "Sint-Michielsbrug, 9000 Gent, Belgium", "St._Michael's_Bridge,_Ghent",
          "Sunset: the famous view of Ghent's three towers", ["Stand at the railing with all three towers lined up behind you"]),
        s("gh-gravensteen", "Gravensteen Castle", "sight", 51.0573, 3.7208, "Sint-Veerleplein 11, 9000 Gent, Belgium", "Gravensteen",
          "Afternoon, from across the water", ["Full-length shot on the bridge with the castle walls behind"]),
        s("gh-st-bavo", "St Bavo's Cathedral", "sight", 51.0530, 3.7267, "Sint-Baafsplein, 9000 Gent, Belgium", "St_Bavo's_Cathedral,_Ghent",
          "Morning; see the Ghent Altarpiece inside", ["Looking up at the tower from the square"]),
        s("gh-belfry", "Belfry of Ghent", "sight", 51.0536, 3.7247, "Sint-Baafsplein, 9000 Gent, Belgium", "Belfry_of_Ghent",
          "Go up for the view at golden hour", ["City panorama from the top, you at the window edge"]),
        s("gh-graffiti", "Werregarenstraat (Graffiti Street)", "photo", 51.0551, 3.7244, "Werregarenstraat, 9000 Gent, Belgium", "Werregarenstraat",
          "Any time; the art changes constantly", ["Lean against the most colourful wall, outfit contrasting the paint"]),
        s("gh-patershol", "Patershol", "food", 51.0581, 3.7225, "Patershol, 9000 Gent, Belgium", "Patershol",
          "Dinner time, when the cobbled lanes are lit", ["Candid walking shot down the narrow lanes"]),
        s("gh-vrijdagmarkt", "Vrijdagmarkt", "sight", 51.0569, 3.7262, "Vrijdagmarkt, 9000 Gent, Belgium", "Vrijdagmarkt",
          "Friday market mornings", ["Wide shot of the colourful square with you in the centre"]),
      ],
    },
    {
      id: "paris", name: "Paris", center: [48.8600, 2.3200], zoom: 13,
      spots: [
        s("pa-trocadero", "Trocadéro (Eiffel Tower view)", "photo", 48.8616, 2.2893, "Place du Trocadéro, 75116 Paris, France", "Trocadéro",
          "Sunrise for an empty terrace; the tower sparkles on the hour after dark", ["Jump shot with the tower in the background", "Back to the camera, arms open toward the tower"]),
        s("pa-eiffel", "Eiffel Tower", "sight", 48.8584, 2.2945, "Champ de Mars, 5 Av. Anatole France, 75007 Paris, France", "Eiffel_Tower",
          "Golden hour from the Champ de Mars", ["Picnic flat-lay on the Champ de Mars lawn, tower behind"]),
        s("pa-bir-hakeim", "Pont de Bir-Hakeim", "photo", 48.8556, 2.2876, "Pont de Bir-Hakeim, 75015 Paris, France", "Pont_de_Bir-Hakeim",
          "Early morning, when the columns frame the tower", ["Walk between the iron columns, symmetrical shot down the middle"]),
        s("pa-louvre", "Louvre Pyramid", "sight", 48.8611, 2.3358, "Rue de Rivoli, 75001 Paris, France", "Louvre_Pyramid",
          "Blue hour, when the pyramid lights up", ["Forced-perspective shot 'touching' the pyramid tip", "Sit on the fountain edge with the pyramid behind"]),
        s("pa-palais-royal", "Palais-Royal Columns", "photo", 48.8635, 2.3370, "8 Rue de Montpensier, 75001 Paris, France", "Les_Deux_Plateaux",
          "Soft morning light", ["Stand on a striped column, shot from low"]),
        s("pa-alexandre-iii", "Pont Alexandre III", "photo", 48.8639, 2.3136, "Pont Alexandre III, 75008 Paris, France", "Pont_Alexandre_III",
          "Sunset, with the golden statues lit", ["Leaning on the ornate lamp post, Eiffel Tower in the distance"]),
        s("pa-arc", "Arc de Triomphe", "sight", 48.8738, 2.2950, "Place Charles de Gaulle, 75008 Paris, France", "Arc_de_Triomphe",
          "Sunset from the rooftop", ["Rooftop shot with the Champs-Élysées behind you"]),
        s("pa-sacre-coeur", "Sacré-Cœur", "sight", 48.8867, 2.3431, "35 Rue du Chevalier de la Barre, 75018 Paris, France", "Sacré-Cœur,_Paris",
          "Sunrise, with the city view from the steps", ["Sit on the steps with Paris spread out below"]),
        s("pa-consulat", "Le Consulat (Montmartre)", "food", 48.8866, 2.3404, "18 Rue Norvins, 75018 Paris, France", null,
          "Morning coffee", ["Coffee at a corner table with the café sign above you"]),
        s("pa-cremieux", "Rue Crémieux", "photo", 48.8461, 2.3714, "Rue Crémieux, 75012 Paris, France", "Rue_Crémieux",
          "Weekday mornings; residents ask visitors to be quiet", ["Walking past the pastel houses, candid"]),
        s("pa-flore", "Café de Flore", "food", 48.8541, 2.3326, "172 Bd Saint-Germain, 75006 Paris, France", "Café_de_Flore",
          "Late morning on the terrace", ["Croissant and coffee shot at a terrace table"]),
        s("pa-shakespeare", "Shakespeare and Company", "shop", 48.8526, 2.3471, "37 Rue de la Bûcherie, 75005 Paris, France", "Shakespeare_and_Company_(bookstore)",
          "Opening time; no photos inside", ["Browsing the green book stalls outside"]),
      ],
    },
    {
      id: "amsterdam", name: "Amsterdam", center: [52.3690, 4.8930], zoom: 14,
      spots: [
        s("am-rijksmuseum", "Rijksmuseum", "sight", 52.3600, 4.8852, "Museumstraat 1, 1071 XX Amsterdam, Netherlands", "Rijksmuseum",
          "Morning, before it opens", ["Cycle or walk through the passage under the museum"]),
        s("am-reguliersgracht", "Reguliersgracht (Seven Bridges)", "photo", 52.3632, 4.8961, "Reguliersgracht, 1017 Amsterdam, Netherlands", "Reguliersgracht",
          "Blue hour, when the bridges light up", ["Stand on the bridge so the row of arches lines up behind you"]),
        s("am-magere-brug", "Magere Brug", "photo", 52.3634, 4.9025, "Kerkstraat, 1017 GM Amsterdam, Netherlands", "Magere_Brug",
          "After dark, when it's lit with bulbs", ["Walking across with the lights glowing behind"]),
        s("am-bloemgracht", "Bloemgracht (Jordaan)", "photo", 52.3743, 4.8817, "Bloemgracht, 1016 Amsterdam, Netherlands", "Bloemgracht",
          "Morning; bikes and flowers everywhere", ["Holding a bike by the canal railing", "Sitting on a canal house stoop"]),
        s("am-anne-frank", "Anne Frank House", "sight", 52.3752, 4.8840, "Westermarkt 20, 1016 GV Amsterdam, Netherlands", "Anne_Frank_House",
          "Book tickets weeks ahead; be respectful", []),
        s("am-bloemenmarkt", "Bloemenmarkt", "shop", 52.3667, 4.8916, "Singel, 1012 DH Amsterdam, Netherlands", "Bloemenmarkt",
          "Spring for fresh tulips", ["Holding a tulip bunch in front of the stalls"]),
        s("am-dam", "Dam Square & Royal Palace", "sight", 52.3731, 4.8926, "Dam, 1012 JS Amsterdam, Netherlands", "Royal_Palace_of_Amsterdam",
          "Early morning", ["Wide shot with the palace facade behind you"]),
        s("am-dancing-houses", "Dancing Houses (Damrak)", "photo", 52.3757, 4.8966, "Damrak, 1012 Amsterdam, Netherlands", "Damrak",
          "Golden hour from across the water", ["Tilted-house shot from the water's edge"]),
        s("am-vondelpark", "Vondelpark", "photo", 52.3580, 4.8686, "Vondelpark, 1071 AA Amsterdam, Netherlands", "Vondelpark",
          "Autumn mornings", ["Cycling down the tree-lined path"]),
        s("am-adam", "A'DAM Lookout", "photo", 52.3843, 4.9019, "Overhoeksplein 5, 1031 KS Amsterdam, Netherlands", "A'DAM_Toren",
          "Sunset over the IJ", ["Over-the-edge swing shot", "City panorama from the rooftop"]),
        s("am-smalle", "Café 't Smalle", "food", 52.3770, 4.8833, "Egelantiersgracht 12, 1015 RL Amsterdam, Netherlands", null,
          "Late afternoon on the canal-side terrace", ["Drinks on the tiny canal terrace"]),
      ],
    },
    {
      id: "luxembourg", name: "Luxembourg", center: [49.6110, 6.1330], zoom: 15,
      spots: [
        s("lu-corniche", "Chemin de la Corniche", "photo", 49.6111, 6.1365, "Chemin de la Corniche, 1945 Luxembourg", "Chemin_de_la_Corniche",
          "Morning light over the Grund", ["Leaning on the wall with the Grund valley behind you"]),
        s("lu-grund", "Grund & Neumünster Abbey", "photo", 49.6097, 6.1373, "28 Rue Münster, 2160 Luxembourg", "Neumünster_Abbey",
          "Late afternoon by the Alzette river", ["Walking on the riverside path with the abbey behind", "Sitting on the little stone bridge"]),
        s("lu-bock", "Bock Casemates", "sight", 49.6117, 6.1373, "10 Mont Saint-Michel, 1222 Luxembourg", "Casemates_du_Bock",
          "Midday; windows frame the valley", ["Silhouette in a stone window opening"]),
        s("lu-palace", "Grand Ducal Palace", "sight", 49.6112, 6.1323, "17 Rue du Marché-aux-Herbes, 1728 Luxembourg", "Grand_Ducal_Palace,_Luxembourg",
          "Morning, before the guard change", ["Symmetrical shot in front of the facade"]),
        s("lu-cathedral", "Notre-Dame Cathedral", "sight", 49.6097, 6.1315, "Rue Notre Dame, 2240 Luxembourg", "Notre-Dame_Cathedral,_Luxembourg",
          "Afternoon", ["Looking up at the spires from the side street"]),
        s("lu-adolphe", "Adolphe Bridge", "photo", 49.6075, 6.1280, "Pont Adolphe, Luxembourg", "Adolphe_Bridge",
          "Sunset from the Pétrusse valley", ["Shot from the valley below with the arch above you"]),
        s("lu-guillaume", "Place Guillaume II", "sight", 49.6107, 6.1305, "Place Guillaume II, 1648 Luxembourg", "Place_Guillaume_II",
          "Market mornings (Wednesday and Saturday)", ["Walking past the market stalls"]),
        s("lu-pfaffenthal", "Pfaffenthal Panoramic Lift", "photo", 49.6141, 6.1308, "Rue du Pont, 2344 Luxembourg", "Pfaffenthal_Panoramic_Elevator",
          "Golden hour", ["Glass-floor shot looking down", "Valley view from the top platform"]),
        s("lu-place-armes", "Place d'Armes", "food", 49.6115, 6.1294, "Place d'Armes, 1136 Luxembourg", "Place_d'Armes,_Luxembourg",
          "Evening terraces", ["Café table shot under the trees"]),
      ],
    },
  ];
})();

// "Paris weekend": the Saturday + Sunday plan from Graciella's itinerary doc,
// with every pin from her Canva map (Google Maps positions). Each stop has
// its planned time (`at`, none for extra pins inside a doc row), visit
// length (`stay`, 0 = walk-by), how to get there (`via`, as written in the
// doc), the doc's note, the Canva notes (`info`) and the Google Maps search
// from the Canva link (`gmaps`). Ids starting with "pa-" reuse ready-made
// Paris spots so their saved inspiration stays.
(() => {
  // "5 min walk", "20 min Metro", "1 hr 45 mins" → minutes.
  const mins = (t) => (Number((/(\d+)\s*hr/.exec(t) || [])[1] || 0) * 60) + Number((/(\d+)\s*min/.exec(t) || [])[1] || 0);
  const via = (how, extra = {}) => (how === "-" ? { how: "", mins: 0, ...extra } : how ? { how, mins: mins(how), ...extra } : null);
  // stop(at, stay, how, id, name, category, lat, lng, address, note, info, gmaps, wiki)
  const stop = (at, stay, how, id, name, category, lat, lng, address, note, info, gmaps, wiki = null) =>
    ({ at, stay, via: via(how), id, name, category, lat, lng, address, note, info, gmaps, wiki, poses: [] });
  const part = (row) => `Part of the ${row} stop.`;
  const day1 = [
    stop("16:05", 5, "5 min walk", "pw-garnier", "Opéra Garnier (Exterior)", "sight", 48.8719697, 2.3316014, "Pl. de l'Opéra, 75009 Paris, France", "Exterior photos only.", "Paid inside · closes 17:00", "Opéra Garnier", "Palais_Garnier"),
    stop("16:30", 25, null, "pw-soubise", "National Archives / Hôtel de Soubise", "sight", 48.8604062, 2.3577888, "60 Rue des Francs Bourgeois, 75003 Paris, France", "Free interior access; closes at 17:30.", "FREE inside; standard close 17:30 · Brief visit", "Hôtel de Soubise Paris", "Hôtel_de_Soubise"),
    stop("17:00", 5, "5 min walk", "pw-lamoignon", "Hôtel de Lamoignon", "photo", 48.8569229, 2.3618595, "24 Rue Pavée, 75004 Paris, France", "Quick courtyard photo.", "Quick courtyard photo if accessible · Library closes 18:00; no palace tour", "Hôtel de Lamoignon Paris", "Hôtel_Lamoignon"),
    stop("17:10", 5, "5 min walk", "pw-carnavalet", "Carnavalet (Exterior)", "sight", 48.8570669, 2.3628579, "23 Rue de Sévigné, 75003 Paris, France", "Exterior photo stop.", "Permanent collection FREE · Last entry 17:15; closes 18:00 · Courtyard access not guaranteed", "Musée Carnavalet Paris", "Musée_Carnavalet"),
    stop("17:20", 10, "5 min walk", "pw-vosges", "Place des Vosges", "photo", 48.8556114, 2.3655266, "Pl. des Vosges, 75004 Paris, France", "Free square and arcades.", "FREE square / arcades · Central garden has gates", "Place des Vosges Paris", "Place_des_Vosges"),
    stop("17:35", 5, "5 min walk", "pw-sully", "Hôtel de Sully", "photo", 48.8543941, 2.3637542, "62 Rue Saint-Antoine, 75004 Paris, France", "Quick exterior/courtyard photo stop.", "FREE courtyard & garden; closes 19:00 · Interiors not freely open", "Hôtel de Sully Paris", "Hôtel_de_Sully"),
    stop(null, 0, null, "pw-st-paul", "Saint-Paul-Saint-Louis", "sight", 48.8544675, 2.3614508, "99 Rue Saint-Antoine, 75004 Paris, France", "Walk-by on the Left Bank walk.", "FREE church; closes 20:00 · Exterior photo; skip if running late", "Église Saint-Paul-Saint-Louis Paris", "Saint-Paul-Saint-Louis"),
    stop(null, 0, null, "pw-pont-sully", "Pont de Sully", "photo", 48.8498408, 2.3580242, "Quai de la Tournelle, Bd Henri IV, 75005 Paris, France", "Walk-by on the Left Bank walk.", "FREE public bridge / quick photo", "Pont de Sully Paris", "Pont_de_Sully"),
    stop(null, 0, null, "pw-ima", "Arab World Institute (Exterior)", "sight", 48.8489257, 2.3572313, "1 Rue des Fossés Saint-Bernard, 75005 Paris, France", "Walk-by on the Left Bank walk.", "Museum ticketed; weekend close 19:00", "Institut du Monde Arabe Paris", "Arab_World_Institute"),
    stop(null, 0, null, "pw-st-etienne", "Saint-Étienne-du-Mont", "sight", 48.8465392, 2.3480897, "Place Sainte-Geneviève, 75005 Paris, France", "Walk-by on the Left Bank walk.", "FREE church; exterior photo planned · Worship may limit indoor visits", "Église Saint-Étienne-du-Mont Paris", "Saint-Étienne-du-Mont"),
    stop("18:10", 5, null, "pw-pantheon", "Panthéon (Exterior)", "sight", 48.8462218, 2.3464138, "Pl. du Panthéon, 75005 Paris, France", "Quick exterior photo.", "Inside paid; last entry 17:15, closes 18:00", "Panthéon Paris", "Panthéon"),
    stop("18:20", 20, "5 min walk to the gate", "pw-luxembourg", "Luxembourg Garden", "photo", 48.8466144, 2.3363309, "Jardin du Luxembourg, 75006 Paris, France", "Enjoy the gardens before the 18:45 closure. Enter by the Rue Soufflot / Médicis side, closest to the Panthéon.", "FREE · Aim to enter 18:20; closes 18:45", "Jardin du Luxembourg Paris", "Jardin_du_Luxembourg"),
    stop("18:45", 5, "5 min walk", "pw-choupinet", "Le Choupinet", "food", 48.8476555, 2.3407853, "58 Bd Saint-Michel, 75006 Paris, France", "Quick exterior photo.", "Exterior photo FREE · Food / drinks cost extra", "Le Choupinet, 58 Boulevard Saint-Michel, 75006 Paris"),
    stop(null, 0, null, "pw-sorbonne", "Place de la Sorbonne", "photo", 48.8487484, 2.3422991, "Pl. de la Sorbonne, 75005 Paris, France", part("18:45 Le Choupinet & Sorbonne"), "FREE square · exterior photo · Chapel interior not included", "Place de la Sorbonne Paris", "University_of_Paris"),
    stop("18:55", 5, "5 min walk", "pw-cluny", "Musée de Cluny (Exterior)", "sight", 48.8504833, 2.3440808, "28 Rue du Sommerard, 75005 Paris, France", "Quick exterior photo.", "Paid inside; closes 18:15 · Exterior only at our arrival", "Musée de Cluny Paris", "Musée_de_Cluny"),
    stop("19:05", 5, "5 min walk", "pw-st-michel", "Fontaine Saint-Michel", "photo", 48.8532372, 2.3437736, "Pl. Saint-Michel, 75005 Paris, France", "Quick photo stop.", "FREE public fountain", "Fontaine Saint-Michel Paris", "Fontaine_Saint-Michel"),
    stop(null, 0, null, "pw-huchette", "Rue de la Huchette", "photo", 48.8530622, 2.3454414, "Rue de la Huchette, 75005 Paris, France", part("19:05 Fontaine Saint-Michel & Huchette"), "FREE street · quick photo", "Rue de la Huchette Paris", "Rue_de_la_Huchette"),
    stop("19:15", 10, "5 min walk", "pa-shakespeare", "Shakespeare & Company", "shop", 48.8525632, 2.3471303, "37 Rue de la Bûcherie, 75005 Paris, France", "Free browsing.", "FREE browsing; closes 21:00 · Exterior photo if there is a queue", "Shakespeare and Company Paris", "Shakespeare_and_Company_(bookstore)"),
    stop("19:30", 15, "5 min walk", "pw-notre-dame", "Notre-Dame (Exterior)", "sight", 48.8529682, 2.3499021, "6 Parvis Notre-Dame - Pl. Jean-Paul II, 75004 Paris, France", "Extended exterior visit.", "Cathedral FREE; closes 19:30 · Indoor visit not in this schedule", "Cathédrale Notre-Dame de Paris", "Notre-Dame_de_Paris"),
    stop("19:50", 5, "10 min walk", "pw-conciergerie", "Palais de Justice", "sight", 48.8557234, 2.3451467, "8 Bd du Palais, 75001 Paris, France", "Quick exterior photo.", "FREE street-side photo · No casual interior visit planned", "Palais de Justice Paris", "Palais_de_Justice,_Paris"),
    stop(null, 0, null, "pw-clock", "Clock / Conciergerie", "photo", 48.8560114, 2.3454953, "2 Bd du Palais, 75001 Paris, France", part("19:50 Palais de Justice & Conciergerie"), "Exterior FREE; interior paid · Last entry 17:30; closes 18:00", "Conciergerie Paris", "Conciergerie"),
    stop("20:05", 5, "5 min walk", "pw-pont-neuf", "Henri IV Statue & Pont Neuf", "photo", 48.8571638, 2.3409791, "15 Pl. du Pont-Neuf, 75001 Paris, France", "Quick photo stop next to the pier.", "FREE public monument", "Statue Henri IV Pont Neuf Paris", "Pont_Neuf"),
    stop("20:15", 30, "2 min walk", "pw-dinner", "Dinner: Restaurant Paul (escargots)", "food", 48.8563303, 2.3422628, "15 Pl. Dauphine, 75001 Paris, France", "Escargots de Bourgogne on the romantic Place Dauphine terrace before checking in for the cruise.", "Dinner from 19:00 · about €20–60 · 4.2★ · Book a 20:15 table, order the escargots right away and ask for the bill with them: the pier is 2 min away, arrive by 20:45", "Restaurant Paul, 15 Place Dauphine, 75001 Paris"),
    stop("20:45", 105, "-", "pw-cruise", "Seine Cruise (Vedettes du Pont Neuf)", "sight", 48.8574484, 2.3409317, "1 Square du Vert Galant, 75001 Paris, France", "Arrive by 20:45 for the 21:15 departure.", "BOOKED · Arrive 20:45; 21:00 latest per ticket · Departs 21:15 · Allow until 22:30 for return", "Vedettes du Pont Neuf Paris"),
  ];
  // The doc's travel rows belong to the stop they lead to.
  day1[1].via = via("20 min Metro", { at: "16:10", label: "Metro to the Marais", note: "Take the metro to the Archives area." });
  day1[6].via = { how: "30 min walk to the Panthéon", mins: null, at: "17:40", label: "Transit Walk: The Left Bank",
    note: "Brisk walk passing Saint-Paul-Saint-Louis, Pont de Sully, Arab World Institute, and Saint-Étienne-du-Mont." };
  const day2 = [
    stop("08:35", 0, "5 min walk", "pw-cour-rome", "Gare Saint-Lazare - Cour de Rome", "photo", 48.8758885, 2.3240292, "Cour de Rome, 75008 Paris, France", "Quick photo without stopping.", "", "Cour de Rome Gare Saint-Lazare Paris", "Gare_Saint-Lazare"),
    stop("08:45", 0, "10 min walk", "pw-augustin", "Église Saint-Augustin", "sight", 48.8762338, 2.3189491, "Pl. Saint-Augustin, 75008 Paris, France", "Quick exterior photo on the move.", "", "Église Saint-Augustin Paris", "Saint-Augustin,_Paris"),
    stop("09:00", 30, "15 min walk", "pw-monceau", "Parc Monceau", "photo", 48.8796835, 2.308955, "Parc Monceau, 75008 Paris, France", "Dedicated time for a morning stroll.", "", "Parc Monceau Paris", "Parc_Monceau"),
    stop("09:35", 0, "5 min walk", "pw-nevsky", "Cathedrale Saint Alexandre Nevsky", "sight", 48.8776402, 2.3019207, "12 Rue Daru, 75008 Paris, France", "Quick photo as you pass.", "", "Cathédrale Saint-Alexandre-Nevsky Paris", "Alexander_Nevsky_Cathedral,_Paris"),
    stop("09:45", 15, "10 min walk", "pa-arc", "Arc de Triomphe", "sight", 48.8737917, 2.2950275, "Pl. Charles de Gaulle, 75008 Paris, France", "View from the crosswalks and base.", "", "Arc de Triomphe", "Arc_de_Triomphe"),
    stop("10:05", 0, "5 min walk", "pw-133-champs", "133 Av. des Champs-Élysées", "photo", 48.8727017, 2.2973426, "133 Av. des Champs-Élysées, 75008 Paris, France", "Snap a photo while walking down the avenue.", "", "133 Avenue des Champs-Élysées"),
    stop("10:15", 0, "10 min walk", "pw-etats-unis", "Place des États-Unis", "photo", 48.8678173, 2.2939776, "Pl. des États-Unis, 75116 Paris, France", "Continuous walking photo.", "", "Place des États-Unis", "Place_des_États-Unis"),
    stop(null, 0, null, "pw-baccarat", "Maison Baccarat", "shop", 48.8676966, 2.2937018, "11 Pl. des États-Unis, 75116 Paris, France", part("10:15 Place des États-Unis & Baccarat"), "", "Maison Baccarat Paris"),
    stop("10:20", 0, "5 min walk", "pw-guimet", "Musée Guimet", "sight", 48.8651018, 2.2937604, "6 Pl. d'Iéna, 75116 Paris, France", "Continuous walking photo.", "", "Musée Guimet Paris", "Musée_Guimet"),
    stop("10:30", 10, "10 min walk", "pa-trocadero", "Palais de Chaillot", "photo", 48.8623687, 2.2881512, "1 Pl. du Trocadéro et du 11 Novembre, 75016 Paris, France", "Stop for the iconic elevated Eiffel Tower view.", "", "Palais de Chaillot Paris", "Palais_de_Chaillot"),
    stop(null, 0, null, "pw-troca-esplanade", "Trocadéro Esplanade", "photo", 48.8621498, 2.2884502, "Espl. du Trocadéro, 75116 Paris, France", part("10:30 Palais de Chaillot & Trocadéro"), "", "Esplanade du Trocadéro Paris"),
    stop(null, 0, null, "pw-troca-gardens", "Trocadéro Gardens", "photo", 48.8616885, 2.2892799, "Pl. du Trocadéro et du 11 Novembre, 75016 Paris, France", part("10:30 Palais de Chaillot & Trocadéro"), "", "Jardins du Trocadéro Paris", "Jardins_du_Trocadéro"),
    stop("10:55", 20, "15 min walk", "pa-eiffel", "Eiffel Tower (Free Esplanade)", "sight", 48.8583701, 2.2944813, "Av. Gustave Eiffel, 75007 Paris, France", "Walk under and around the base.", "", "Tour Eiffel esplanade Paris", "Eiffel_Tower"),
    stop("11:20", 5, "5 min walk", "pw-universite", "Rue de l'Université", "photo", 48.860325, 2.297641, "218 Rue de l'Université, 75007 Paris, France", "Stop for the classic street-level view.", "", "218 Rue de l'Université Paris"),
    stop("11:30", 0, "5 min walk", "pw-branly", "Musée du quai Branly - Jacques Chirac", "sight", 48.8608889, 2.297894, "37 Quai Jacques Chirac, 75007 Paris, France", "View the exterior green wall as you walk.", "", "Musée du quai Branly green wall, 218 Rue de l'Université, 75007 Paris", "Musée_du_quai_Branly_–_Jacques_Chirac"),
    stop("11:35", 0, "5 min walk", "pw-trinite", "Cathédrale de la Sainte-Trinité", "sight", 48.8619251, 2.3010086, "1 Quai Jacques Chirac, 75007 Paris, France", "Quick photo of the domes.", "", "Sainte-Trinité Quai Branly", "Holy_Trinity_Cathedral,_Paris"),
    stop("11:45", 0, "10 min walk", "pw-invalides-bridge", "Quai d'Orsay & Pont des Invalides", "photo", 48.8635777, 2.3104289, "Pont des Invalides, 75007 Paris, France", "Riverside walk.", "Exterior photo FREE", "Pont des Invalides", "Pont_des_Invalides"),
    stop("11:50", 5, "5 min walk", "pa-alexandre-iii", "Pont Alexandre III", "photo", 48.8638995, 2.313559, "Pont Alexandre III, 75008 Paris, France", "Brief stop to appreciate the bridge details.", "", "Pont Alexandre III Paris", "Pont_Alexandre_III"),
    stop("12:00", 0, "5 min walk", "pw-palais", "Grand Palais", "sight", 48.8661091, 2.3124544, "Grand Palais, 75008 Paris, France", "Exterior photos while walking past.", "", "Grand Palais Paris", "Grand_Palais"),
    stop(null, 0, null, "pw-petit-palais", "Petit Palais", "sight", 48.8660479, 2.3145896, "Av. Winston Churchill, 75008 Paris, France", part("12:00 Grand Palais & Petit Palais"), "", "Petit Palais Paris", "Petit_Palais"),
    stop("12:10", 0, "10 min walk", "pw-concorde", "Obélisque de Louxor (Place de la Concorde)", "sight", 48.8654831, 2.3211309, "Pl. de la Concorde, 75008 Paris, France", "View the Obelisk and fountain while crossing.", "Exterior FREE", "Obélisque de Louxor", "Luxor_Obelisk"),
    stop(null, 0, null, "pw-fontaine-mers", "Fontaine des Mers", "photo", 48.8649629, 2.3207592, "Pl. de la Concorde, 75008 Paris, France", part("12:10 Place de la Concorde"), "", "Fontaine des Mers Paris", "Fontaine_des_Mers"),
    stop("12:15", 10, "5 min walk", "pw-tuileries", "Jardin des Tuileries", "photo", 48.8634916, 2.3274943, "Jardin des Tuileries, 75001 Paris, France", "Brisk pace through the main garden path.", "", "Jardin des Tuileries Paris", "Tuileries_Garden"),
    stop(null, 0, null, "pw-bassin", "Grand Bassin Rond", "photo", 48.8628913, 2.3293022, "Allée Centrale, Jardin des Tuileries, 75001 Paris, France", part("12:15 Jardin des Tuileries & Grand Bassin"), "", "Grand Bassin Rond Tuileries Paris"),
    stop(null, 0, null, "pw-carrousel-garden", "Jardin du Carrousel", "photo", 48.8619966, 2.3320701, "6 Av. du Général Lemonnier, 75001 Paris, France", "On the way to the Arc de Triomphe du Carrousel (from the Canva map).", "", "Jardin du Carrousel Paris"),
    stop("12:35", 0, "10 min walk", "pw-carrousel", "Arc de Triomphe du Carrousel", "photo", 48.861713, 2.3328946, "Pl. du Carrousel, 75001 Paris, France", "Quick photo.", "", "Arc de Triomphe du Carrousel Paris", "Arc_de_Triomphe_du_Carrousel"),
    stop("12:40", 10, "5 min walk", "pa-louvre", "Louvre (Courtyard/Pyramid)", "sight", 48.8610135, 2.3358583, "Cour Napoléon, 75001 Paris, France", "Photo stop at the glass pyramids.", "", "Pyramide du Louvre Paris", "Louvre_Pyramid"),
    stop("13:00", 5, "10 min walk", "pa-palais-royal", "Colonnes de Buren", "photo", 48.863612, 2.3370336, "2 Rue de Montpensier, 75001 Paris, France", "Stop at the striped columns.", "", "Colonnes de Buren Palais-Royal Paris", "Les_Deux_Plateaux"),
    stop(null, 0, null, "pw-palais-royal-garden", "Jardin du Palais-Royal", "photo", 48.8649723, 2.3378061, "8 Rue de Montpensier, 75001 Paris, France", part("13:00 Palais Royal & Colonnes de Buren"), "", "Jardin du Palais-Royal Paris", "Palais-Royal"),
    stop("13:10", 5, "5 min walk", "pw-vivienne", "Galerie Vivienne", "photo", 48.8663591, 2.339491, "4 Rue des Petits Champs, 75002 Paris, France", "Walk through the covered passage.", "", "Galerie Vivienne, 4 Rue des Petits-Champs, 75002 Paris", "Galerie_Vivienne"),
    stop("13:30", 25, "15 min walk", "pw-lafayette", "Galeries Lafayette", "shop", 48.8736224, 2.3321099, "40 Bd Haussmann, 75009 Paris, France", "View the dome interior and rooftop views, grab a snack.", "", "Galeries Lafayette Paris Haussmann", "Galeries_Lafayette"),
    stop(null, 0, null, "pw-rooftop", "Galeries Lafayette Rooftop", "photo", 48.873629, 2.332015, "40 Bd Haussmann, 75009 Paris, France", part("13:30 Galeries Lafayette & Rooftop"), "", "Galeries Lafayette rooftop Paris"),
    stop("14:00", 29, "5 min walk", "pw-hotel", "Residhome Paris Opéra", "stay", 48.874757, 2.32909, "30 Rue Joubert, 75009 Paris, France", "Arrive at the hotel to grab your luggage and prepare to leave.", "", "Residhome Paris Opéra, 30 Rue Joubert, 75009 Paris"),
  ];
  window.SEED_PARIS_WEEKEND = {
    version: 4,
    start: { name: "Residhome Paris Opéra", lat: 48.874757, lng: 2.32909 },
    names: ["Saturday", "Sunday"],
    titles: ["The Marais, Latin Quarter & Seine Walk", "West Paris, Eiffel Tower & Louvre"],
    blurbs: [
      "This route relies on a brisk walking pace between stops to ensure you reach the Luxembourg Garden before it closes and make your evening cruise.",
      "This route features \"walk-by\" sightseeing for minor monuments to ensure you get dedicated time at Parc Monceau, the Eiffel Tower, and Galeries Lafayette before your afternoon departure.",
    ],
    departs: ["Depart hotel.", "Depart hotel."],
    finish: [{ at: "22:30", name: "Cruise ends", note: "Hotel / optional dinner afterward." },
      { at: "14:29", name: "Departure", note: "Leave hotel to catch Metro 12." }],
    hours: [{ start: "16:00", end: "22:30" }, { start: "08:30", end: "14:29" }],
    removed: [],
    days: [day1, day2],
  };
})();
